nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:5173'] # URL de ton frontend  #['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        hosts: []
    paths:
        '^/': # null
            allow_origin: ['http://localhost:5173']
